[theme]
base = "light"
primaryColor = "#1268E8"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#121A2D"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
